# -*- coding: utf-8 -*-
"""Python Task .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WiXZdpT3DOOwAhlmeaL-RTInKRCfQJY

**1 Write a Python program to read a CSV file and display its contents.**
"""

import csv

def read_csv_file(filename):
  """Reads a CSV file and displays its contents.

  Args:
    filename: The name of the CSV file.
  """

  with open(filename, 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    for row in csvreader:
      print(row)

if __name__ == '__main__':
  filename = '/content/story.txt'  # Replace with your CSV file name
  read_csv_file(filename)

"""**2. Write a Python function to reverse a string.**

"""

def reverse_string(s):
    return s[::-1]

# Example usage
input_string = "Hello, World!"
reversed_string = reverse_string(input_string)
print(f"Original string: {input_string}")
print(f"Reversed string: {reversed_string}")

"""**3. Write a Python function to count the occurrences of a specific element in a list.**"""

def count_occurrences(lst, element):
    return lst.count(element)

# Example usage
input_list = [1, 2, 3, 4, 2, 2, 5, 2, 6, 2]
element_to_count = 2
occurrences = count_occurrences(input_list, element_to_count)
print(f"Element {element_to_count} occurs {occurrences} times in the list.")

